#!/bin/sh
# If cloudflared is installed through its service command, the update command below will work.
# https://docs.pi-hole.net/guides/dns-over-https/

# To make executable by anacron run the following in your terminal
# sudo chmod +x cloudflared-updater
# sudo chown root:root cloudflared-updater

cloudflared update


# Copyright 2021 Logan Bresnahan

# This file is part of pihole_cron_scripts.

# pihole_cron_scripts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# pihole_cron_scripts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with pihole_cron_scripts. If not, see <https://www.gnu.org/licenses/>.
