#!/bin/sh
# Update Pihole, PiHole's Gravity List, and Restart DNS

# To make executable by anacron run the following in your terminal
# sudo chmod +x pihole-gravity-updater
# sudo chown root:root pihole-gravity-updater

echo "*****Updating Pihole*****"
pihole updatePihole
echo "*****Updating Gravity*****"
pihole updateGravity
echo "*****Restarting DNS*****"
pihole restartdns
echo "*****Showing Pihole Status*****"
pihole status


# Copyright 2021 Logan Bresnahan

# This file is part of pihole_cron_scripts.

# pihole_cron_scripts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# pihole_cron_scripts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with pihole_cron_scripts. If not, see <https://www.gnu.org/licenses/>.
