#!/bin/sh
# This script gets its data from https://firebog.net/ which provides various adlists
# to be used by pihole. This script uses the safest lists which most likely
# will not have false positives.

# To make executable by anacron run the following in your terminal
# sudo chmod +x pihole-adlist-adder
# sudo chown root:root pihole-adlist-adder

ADLISTS_HOST="https://v.firebog.net/hosts/lists.php?type=tick"
echo "Requesting adlists from ${ADLISTS_HOST}"
ADLISTS=$(curl -s $ADLISTS_HOST)

# If we get a list of URL's and not HTML we continue.
if [ $(echo $ADLISTS | cut -c1-8) = "https://" ];
then
  for ADLIST in $ADLISTS
  do
    SELECT_RESULT=$(sudo sqlite3 /etc/pihole/gravity.db \
      'SELECT * FROM adlist WHERE address = "'${ADLIST}'";')

    # If the address doesn't already exist in the adlist table insert it.
    if [ -z "$SELECT_RESULT" ];
    then
      echo "Inserting ${ADLIST} into gravity.db adlist table"

      sudo sqlite3 /etc/pihole/gravity.db \
        'INSERT INTO adlist (address, comment) VALUES("'${ADLIST}'", "Migrated from '${ADLISTS_HOST}'");'
    else
      echo "${ADLIST} already exists"
    fi
  done
else
  echo "Error retrieving adlists from ${ADLISTS_HOST}"
fi
