#!/bin/sh
# This script gets its data from https://firebog.net/ which provides various adlists
# to be used by pihole. This script uses the safest lists which most likely
# will not have false positives.

# To make executable by anacron run the following in your terminal
# sudo chmod +x pihole-adlist-adder-remover
# sudo chown root:root pihole-adlist-adder-remover

DATABASE_PATH="/etc/pihole/gravity.db"
ADLISTS_HOST="https://v.firebog.net/hosts/lists.php?type=tick"
echo "Requesting adlists from ${ADLISTS_HOST}"
ADLISTS=$(curl -s $ADLISTS_HOST)

# If we get a list of URL's and not HTML we continue.
if [ $(echo $ADLISTS | cut -c1-8) = "https://" ];
then
  for ADLIST in $ADLISTS
  do
    SELECT_RESULT=$(sqlite3 $DATABASE_PATH \
      'SELECT * FROM adlist WHERE address = "'${ADLIST}'";')

    # If the address doesn't already exist in the adlist table insert it.
    if [ -z "$SELECT_RESULT" ];
    then
      echo "Inserting ${ADLIST} into gravity.db adlist table"

      sqlite3 $DATABASE_PATH \
        'INSERT INTO adlist (address, comment) VALUES("'${ADLIST}'", "Migrated from '${ADLISTS_HOST}'");'
    else
      echo "${ADLIST} already exists"
    fi
  done

  # Check for stale adlists in our database.
  for RESULT in $(sqlite3 $DATABASE_PATH \
    'SELECT address, enabled FROM adlist WHERE comment = "Migrated from '${ADLISTS_HOST}'";')
  do
    IFS="|"; set -- $RESULT
    ADDRESS=$1
    ENABLED=$2
    unset IFS

    EXISTS_ON_ADLISTS_HOST="NO"

    for ADLIST in $ADLISTS
    do
      if [ $ADDRESS = $ADLIST ];
      then
        EXISTS_ON_ADLISTS_HOST="YES"
      fi
    done

    if [ $EXISTS_ON_ADLISTS_HOST != "YES" ] && [ $ENABLED = "1" ];
    then
      echo "Disabling ${ADDRESS}"

      sqlite3 $DATABASE_PATH \
        'UPDATE adlist SET enabled = 0 WHERE address = "'${ADDRESS}'";'
    elif [ $EXISTS_ON_ADLISTS_HOST = "YES" ] && [ $ENABLED = "0" ];
    then
      echo "Re-enabling ${ADDRESS}"

      sqlite3 $DATABASE_PATH \
        'UPDATE adlist SET enabled = 1 WHERE address = "'${ADDRESS}'";'
    fi
  done
else
  echo "Error retrieving adlists from ${ADLISTS_HOST}"
fi


# Copyright 2021 Logan Bresnahan

# This file is part of pihole_cron_scripts.

# pihole_cron_scripts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# pihole_cron_scripts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with pihole_cron_scripts. If not, see <https://www.gnu.org/licenses/>.
